[package]
name = "eiger-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
native-tls = "0.2"
reqwest = { version = "0.11", features = ["json"] }
log = "0.4"
env_logger = "0.9"